version: "3.7"
services:
  node-api:
    build: .
    container_name: node-api
    ports:
      - "3000:3000"
    networks:
      - node_network
  api_db:
    image: mysql:5.7
    container_name: api_db
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=moe_db
    networks:
      - node_network
networks:
  node_network:
    driver: bridge
